CREATE TABLE products(
    p_id int IDENTITY,
    p_name varchar(20) NOT NULL,
    p_price DECIMAL(15,2) NOT NULL,
    p_desc varchar(120),
    p_category varchar(20)
)

alter table products add CONSTRAINT pk_products PRIMARY KEY (p_id)

create table line_items(
    l_id  int IDENTITY,
    l_prod int NOT NULL,
    l_order int,
    l_storefront int,
    l_quantity int NOT NULL,
    CONSTRAINT pk_line_items PRIMARY KEY(l_id),
    CONSTRAINT fk_line_items_products FOREIGN KEY(l_prod) REFERENCES dbo.products (p_id),
    CONSTRAINT fk_line_items_orders FOREIGN KEY(l_order) REFERENCES dbo.orders (o_id),
    CONSTRAINT fk_line_items_store_front FOREIGN KEY(l_storefront) REFERENCES store_front (s_id),
    CONSTRAINT item_inventory_or_order CHECK ((l_order is null or l_storefront is null) and not (l_order is null and l_storefront is null))
)

drop table line_items

CREATE TABLE orders(
    o_id int IDENTITY,
    o_loc VARCHAR(30) NOT NULL,
    o_price DECIMAL(20,2) NOT NULL,
    o_store int NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY(o_id),
    CONSTRAINT fk_orders_store_front FOREIGN KEY(o_store) REFERENCES store_front (s_id)
)
DROP TABLE orders

create table customer(
    c_id int IDENTITY,
    c_name varchar(30),
    c_addr varchar(90),
    c_email varchar(30),
)

create table store_front(
    s_id int IDENTITY,
    c_addr VARCHAR(90),
    CONSTRAINT pk_store_front PRIMARY KEY (s_id)
)
alter table store_front add s_addr VARCHAR(90);

select * from products;

insert into products(name, price) values(
('shirt' 9.89),
('stockings' 2.90),
('thread' 6.80),
('lamp' 8.41),
('sun glasses' 1.02),
('credit card' 0.46),
('teddies' 3.77),
('charger' 5.03),
('magnet' 2.86),
('candy wrapper' 6.34),
('paper' 1.59),
('glass' 1.41),
('pillow' 5.75),
('twister' 2.39),
('ice cube tray' 3.82),
('toilet' 6.72),
('button' 0.08),
('lip gloss' 5.97),
('deodorant' 6.34),
('socks' 7.44),
('shawl' 9.42),
('remote' 6.34),
('perfume' 3.96),
('window' 5.76),
('shoes' 3.29),
('couch' 1.90),
('bow' 7.66),
('television' 7.27),
('ipod' 6.10),
('photo album' 8.38),
('fake flowers' 8.86),
('shampoo' 5.44),
('glasses' 8.56),
('lotion' 6.03),
('rubber duck' 3.82),
('packing peanuts' 4.21),
('bottle' 7.30),
('bag' 8.18),
('tissue box' 6.37),
('nail clippers' 7.38),
('computer' 9.85),
('thermostat' 3.41),
('bowl' 9.23),
('white out' 0.43),
('sidewalk' 7.41),
('screw' 4.36),
('eraser' 3.73),
('chapter book' 2.64),
('headphones' 7.12),
('soap' 5.04),
('sofa' 5.98),
('lamp shade' 7.57),
('needle' 6.38),
('box' 9.44),
('speakers' 3.38),
('wagon' 1.14),
('controller' 4.54),
('tooth picks' 4.81),
('balloon' 9.57),
('paint brush' 0.22),
('rubber band' 0.33),
('hanger' 6.47),
('mop' 5.67),
('vase' 8.89),
('zipper' 9.25),
('helmet' 9.61),
('radio' 1.48),
('key chain' 0.52),
('slipper' 9.42),
('hair tie' 3.82),
('picture frame' 9.40),
('book' 3.89),
('twezzers' 4.34),
('desk' 6.85),
('blouse' 4.14),
('ring' 0.80),
('sponge' 1.92),
('mirror' 5.87),
('flag' 1.17),
('face wash' 1.33),
('USB drive' 9.90),
('video games' 6.57),
('pen' 0.14),
('mp3 player' 2.62),
('stop sign' 1.16),
('toothbrush' 0.35),
('air freshener' 6.20),
('clothes' 3.94),
('watch' 9.22),
('fork' 5.61),
('knife' 1.72),
('water bottle' 2.17),
('wallet' 0.50),
('toothpaste' 1.89),
('phone' 7.62),
('doll' 0.74),
('glow stick' 2.99),
('mouse pad' 4.18),
('beef' 5.86),
('milk' 9.89))